language: d

#compiler:
#  - dmd

install:
  # dmd
  - DMD_VERSION=2.077.0
  - RELEASE_YEAR=2017
  - wget http://downloads.dlang.org/releases/${RELEASE_YEAR}/dmd.${DMD_VERSION}.linux.zip
  - unzip dmd.${DMD_VERSION}.linux.zip

script:
  - DMD=./dmd2/linux/bin64/dmd MODEL=64 make -f posix.mak unittest

branches:
  only:
    - master

notifications:
  email: true
